[package]
name = "compose"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "compose"
crate-type = ["cdylib", "rlib"]

[dependencies]
blitz-compose-core = { path = "../core" }
ffrwd-node.workspace = true
ffrwd-frame.workspace = true
serde.workspace = true
serde_json.workspace = true
