"""Writes THIRD_PARTY_NOTICES: every crate linked into the wasm module, with
its version, license and source, from `cargo metadata`.

"Linked" is the closure of normal dependencies of the module crate on
wasm32-wasip2. Build dependencies and proc-macro crates run at compile time
and are not part of a module, so they are left out.

    PYTHONUTF8=1 python scripts/third_party_notices.py
"""

import collections
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
MODULES = ["compose"]
OURS = {"compose", "blitz-compose-core"}

HEADER = """Third-party notices for ffrwd/blitz

The package's own code is MIT (see LICENSE). The wasm module it builds
(target/wasm32-wasip2/release/compose.wasm) links the crates listed below,
each under its own license: among them Stylo (MPL-2.0), whose source is at
https://github.com/servo/stylo and on crates.io as stylo 0.21.0, and Blitz,
Vello (vello_cpu), Parley, Taffy, fontique, skrifa, usvg and the image
decoders. Where a crate offers a choice of licenses ("A OR B"), the choice
is the recipient's.

The module also embeds the DejaVu Sans font (core/assets/DejaVuSans.woff2),
under the Bitstream Vera license with public-domain DejaVu changes and the
Arev license; the full text is in core/assets/DejaVu-LICENSE.

This list is generated by scripts/third_party_notices.py from `cargo
metadata --filter-platform wasm32-wasip2`: the normal dependencies reachable
from the module crate. Build dependencies and proc-macro crates, which run
only while compiling, are not listed.

"""


def main():
    meta = json.loads(
        subprocess.run(
            ["cargo", "metadata", "--format-version", "1", "--filter-platform", "wasm32-wasip2"],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    )
    packages = {p["id"]: p for p in meta["packages"]}
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    roots = [p["id"] for p in meta["packages"] if p["name"] in MODULES and p["source"] is None]
    seen = set()
    stack = list(roots)
    while stack:
        pid = stack.pop()
        if pid in seen:
            continue
        seen.add(pid)
        for dep in nodes[pid]["deps"]:
            kinds = {k["kind"] for k in dep["dep_kinds"]}
            if None not in kinds:
                continue
            target_kinds = {k for t in packages[dep["pkg"]]["targets"] for k in t["kind"]}
            if "proc-macro" in target_kinds:
                continue
            stack.append(dep["pkg"])
    rows = []
    for pid in seen:
        p = packages[pid]
        if p["name"] in OURS:
            continue
        source = p.get("repository") or ""
        if p["source"] and p["source"].startswith("git+"):
            source = p["source"].split("#")[0].removeprefix("git+")
        rows.append((p["name"], p["version"], p.get("license") or "(see the crate)", source))
    rows.sort()
    by_license = collections.Counter(r[2] for r in rows)
    out = [HEADER]
    out.append(f"{len(rows)} crates, by license:\n\n")
    for lic, n in sorted(by_license.items(), key=lambda x: (-x[1], x[0])):
        out.append(f"  {n:4d}  {lic}\n")
    out.append("\nCrate, version, license, source:\n\n")
    for name, version, lic, source in rows:
        out.append(f"{name} {version}\n    {lic}\n    {source}\n")
    (ROOT / "THIRD_PARTY_NOTICES").write_text("".join(out), encoding="utf-8", newline="\n")
    print(f"{len(rows)} crates")


if __name__ == "__main__":
    main()
